Fix some formatting and typos
permitio/fastapi_websocket_rpc pull request #17
Opened 2022-09-06 17:32 UTC by jsdanielh

- Fix some formatting and typos in several files.
- Rename `RpcUtilityMethods`'s `get_proccess_details` method to
  `get_process_details`.

2022-09-06 20:02 UTC, orweis commented
Hi @jsdanielh !
Thanks for the work here. I'll try to review it all tomorrow, typo fixes look great, there are some type changes I'd need to look more deeply into than a quick skim.

2022-09-07 12:13 UTC, orweis requested changes
Looks great- few comments inline; most not critical, only the float->int change requires further discussion

2022-09-07 12:13 UTC, orweis commented on tests/custom_methods_test.py
> +sys.path.append(os.path.abspath(os.path.join(
This seems inconsistent with the other changes here (preferring to have code in a single line)

2022-09-07 12:13 UTC, orweis commented on tests/fast_api_depends_test.py
> +sys.path.append(os.path.abspath(os.path.join(
This seems inconsistent with the other changes here (preferring to have code in a single line)

2022-09-07 12:13 UTC, orweis commented on tests/trigger_flow_test.py
> +sys.path.append(os.path.abspath(os.path.join(
This seems inconsistent with the other changes here (preferring to have code in a single line)

2022-09-07 17:52 UTC, jsdanielh commented
> Looks great- few comments inline; most not critical, only the float->int change requires further discussion

@orweis I applied your suggestion on the type change for the timeout. I actually went and changed it in some other places that were specifying `int`.
For the line break changes, they go more into complying with [PEP8 maximum line specification](https://peps.python.org/pep-0008/#maximum-line-length). Although I know there are some lines that doesn't fully comply with it, I thought a change towards that path would help. Let me know what you think.

2022-09-08 08:02 UTC, orweis approved these changes
Awesomeness. :)
Thank you @jsdanielh

2022-09-08 08:02 UTC, merged