Add option to get remote channel id
permitio/fastapi_websocket_rpc pull request #8
Opened 2021-10-27 17:28 UTC by obsd

2021-10-30 06:16 UTC, asafc requested changes
Good work @obsd!

I am going to block until we fix the two criticial comments:
1) two methods with same name - `get_other_channel_id()`
2) forgot else block (Or's comment)

fixes should be really quick, almost there!

2021-10-30 06:16 UTC, asafc commented on fastapi_websocket_rpc/rpc_channel.py
> +    async def get_other_channel_id(self) -> str:
you have two methods with the signature `async def get_other_channel_id(self)`:
one here (line 168) and one in line 258.

i assume one of them should be `_get_other_channel_id` with underscore (i assume the one on 258) and that on connect should call `_get_other_channel_id`.

2021-10-30 06:16 UTC, asafc commented on fastapi_websocket_rpc/rpc_channel.py
> +        if self._other_channel_id is None:
super important @obsd

2021-10-31 08:34 UTC, obsd commented on fastapi_websocket_rpc/rpc_channel.py
> +        if self._other_channel_id is None:
fixed both issues and forgot to push :|

2021-10-31 08:35 UTC, obsd commented on fastapi_websocket_rpc/rpc_channel.py
> +            self._other_channel_id = other_channel_id.result if other_channel_id and other_channel_id.result else None
If I have here a None should I raise an error?

2021-10-31 08:47 UTC, obsd commented on fastapi_websocket_rpc/rpc_channel.py
> +            self._other_channel_id = other_channel_id.result if other_channel_id and other_channel_id.result else None
@asafc

2021-11-02 14:16 UTC, asafc approved these changes

2021-11-02 14:16 UTC, merged